version: '3'
services:
  postgres:
    image: 'postgres:9.6.1'
    ports:
      - '2000:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'nest-typeorm'
